### ISSUE TITLE
ea-php70

### ISSUE THREAD

**Issue by surjit** [CpanelInc/scl-php70#2]
Hi

after looking in apache conf. I reached at /usr/local/cpanel/cgi-sys/ea-php70
I craving to understand, how this stuff works  and In binary file I only found this
/opt/cpanel/%s/root/usr/bin/php-cgi DOCUMENT_ROOT PATH_TRANSLATED /usr/bin/php /usr/php4/bin/php Failed to exec Invalid startup Not supported ea-php php version

I understand, may be you can't share source code, I just need idea, or may link to internet source,
how this cgi works

Thanks,

**Comment by HoustonDad** [comment]
Hi,

I'm not sure of the question. All the sources for EA4 are open source and here on github. Are you having issues with something?

**Comment by surjit** [comment]
where i can find the source code of /usr/local/cpanel/cgi-sys/ea-php70 ?

**Comment by HoustonDad** [comment]
Ah, that script itself is not open source, unfortunately the source is not available.

**Comment by surjit** [comment]
can you please give me rough idea, I will really appreciate

**Comment by HoustonDad** [comment]
These are mainly shell scripts that wrap around the cgi script itself...


```#!/bin/sh
exec /opt/cpanel/ea-php54/root/usr/bin/php-cgi```

**Comment by surjit** [comment]
thanks
